# Generated by Django 4.1.7 on 2023-03-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_location_subscribers_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='chat_id',
            field=models.CharField(default=11, max_length=40),
            preserve_default=False,
        ),
    ]
